### PR TITLE
Actually accept this time.

### PR DESCRIPTION
**Pull request by Xoui**

### CODE REVIEW

**Review by dave9123 — CHANGES_REQUESTED** [review]
Flashpoint zip choice isn't showing

**Comment by Xoui** [comment]
So basically. Uh i had 10 commits then that guy closed it. and now I just c&p the old one

**Comment by py660** [comment]
lgtm

**Comment by Xoui** [comment]
u know what IDGAF AT THIS POINT IVE BEEN QUARANTINED FOR NO DAM REASON

**Pull request closed without merging**
